apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-logs
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: loki-logs
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2
    helm:
      values: |
        loki:
          enabled: true

        promtail:
          enabled: true

        fluent-bit:
          enabled: false

        grafana:
          enabled: false

        prometheus:
          enabled: false

        filebeat:
          enabled: false

        logstash:
          enabled: false
  syncPolicy:
    automated: {}
