apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins
    repoURL: https://xaos613.github.io/helm-rep/
    targetRevision: 0.3.1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
